services:
  # django app
  backend:
    container_name: django
    ports:
      - "8000:8000"
    build: .
    command: uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    depends_on:
      - django_redis
      - django_db
  
  # redis for channels
  django_redis:
    container_name: django_redis
    image: "redis"
    ports:
      - "6379:6379"
    
  # postgresql database
  django_db:
    container_name: postgresql
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - .dbdata:/var/lib/postgresql
  
  # celery worker
  celery_worker:
    container_name: blog_celery_worker
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - django_redis
      - django_db
  
  # celery beat scheduler
  celery_beat:
    container_name: blog_celery_beat
    build: .
    command: celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    depends_on:
      - django_redis
      - django_db