# Generated by Django 4.2.24 on 2025-09-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
