# Generated by Django 4.2.24 on 2025-09-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_heading_post_alter_postview_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostAnalitics',
            new_name='PostAnalytics',
        ),
    ]
