# Generated by Django 4.2.24 on 2025-09-18 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_categoryview_categoryanalytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postanalytics',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_analytics', to='blog.post'),
        ),
    ]
